# Generated by Django 5.0.7 on 2025-06-18 01:42

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrideGroomApplication',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('groom_fullname', models.CharField(max_length=100)),
                ('groom_id_number', models.CharField(max_length=20)),
                ('groom_dob', models.DateField()),
                ('groom_nationality', models.CharField(max_length=50)),
                ('groom_religion', models.CharField(max_length=50)),
                ('groom_marital_status', models.CharField(choices=[('BUJANG', 'Bujang'), ('DUDA', 'Duda'), ('JANDA', 'Janda')], max_length=10)),
                ('groom_address', models.TextField()),
                ('groom_ic_copy', models.FileField(upload_to='applications/groom/ic/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('groom_hiv_test', models.FileField(upload_to='applications/groom/hiv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('groom_marriage_course', models.FileField(upload_to='applications/groom/course/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('bride_fullname', models.CharField(max_length=100)),
                ('bride_id_number', models.CharField(max_length=20)),
                ('bride_dob', models.DateField()),
                ('bride_nationality', models.CharField(max_length=50)),
                ('bride_religion', models.CharField(max_length=50)),
                ('bride_marital_status', models.CharField(choices=[('BUJANG', 'Bujang'), ('DUDA', 'Duda'), ('JANDA', 'Janda')], max_length=10)),
                ('bride_address', models.TextField()),
                ('wali_name', models.CharField(max_length=100)),
                ('wali_ic', models.CharField(max_length=20)),
                ('bride_ic_copy', models.FileField(upload_to='applications/bride/ic/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('bride_hiv_test', models.FileField(upload_to='applications/bride/hiv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('bride_marriage_course', models.FileField(upload_to='applications/bride/course/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('wali_ic_copy', models.FileField(upload_to='applications/wali/ic/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('wali_consent', models.FileField(upload_to='applications/wali/consent/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.CharField(default='No remarks yet', max_length=100),
            preserve_default=False,
        ),
    ]
