# Generated by Django 5.0.7 on 2025-06-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0002_bridegroomapplication_user_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
