# Generated by Django 5.0.7 on 2025-06-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0003_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridegroomapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='NikahFlow.user'),
        ),
    ]
