# Generated by Django 5.0.7 on 2025-06-22 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0004_bridegroomapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImamAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Not Available'), ('pending', 'Pending Submission')], default='pending', max_length=20)),
                ('time_slots', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='NikahFlow.user')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('imam', 'date')},
            },
        ),
    ]
