# Generated by Django 5.0.7 on 2025-06-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0005_imamavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolemnisationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Not Available'), ('pending', 'Pending Submission')], default='pending', max_length=20)),
                ('time_slots', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('status', 'date')},
            },
        ),
    ]
