# Generated by Django 5.0.7 on 2025-06-24 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0006_solemnisationslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolemnisationBooking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('date', models.DateField()),
                ('time_slots', models.JSONField(default=list)),
                ('specific_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='NikahFlow.user')),
            ],
        ),
    ]
