# Generated by Django 5.0.7 on 2025-06-24 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0007_solemnisationbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solemnisationbooking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='solemnisationbooking',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='solemnisationbooking',
            name='location',
            field=models.CharField(default=datetime.date(2025, 4, 11), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solemnisationbooking',
            name='time_slot',
            field=models.CharField(default='morning', max_length=20),
            preserve_default=False,
        ),
    ]
