# Generated by Django 5.0.7 on 2025-06-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0008_rename_date_solemnisationbooking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridegroomapplication',
            name='remarks',
            field=models.CharField(default='No remarks yet', max_length=100),
            preserve_default=False,
        ),
    ]
