# Generated by Django 5.0.7 on 2025-06-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0009_bridegroomapplication_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
