# Generated by Django 5.0.7 on 2025-06-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solemnisationbooking',
            name='bride_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solemnisationbooking',
            name='groom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
