# Generated by Django 5.0.7 on 2025-06-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0011_solemnisationbooking_bride_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImamSolemnisationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_assignments', to='NikahFlow.solemnisationbooking')),
                ('imam', models.ForeignKey(limit_choices_to={'role': 'imam'}, on_delete=django.db.models.deletion.CASCADE, related_name='solemnisation_assignments', to='NikahFlow.user')),
            ],
            options={
                'verbose_name': 'Imam Assignment',
                'verbose_name_plural': 'Imam Assignments',
                'unique_together': {('imam', 'booking')},
            },
        ),
    ]
