# Generated by Django 5.0.7 on 2025-06-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0012_imamsolemnisationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='solemnisationbooking',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
