# Generated by Django 5.0.7 on 2025-07-06 23:56

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0013_solemnisationbooking_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='solemnisationbooking',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solemnisationbooking',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Report ID')),
                ('month', models.DateField(help_text='Month and year of the report (day will be ignored)')),
                ('total_applications', models.PositiveIntegerField(default=0, verbose_name='Total Applications')),
                ('approved_applications', models.PositiveIntegerField(default=0, verbose_name='Approved Applications')),
                ('solemnisation_count', models.PositiveIntegerField(default=0, verbose_name='Solemnisation Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'adminchairman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reports', to='NikahFlow.user', verbose_name='Admin Chairman')),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-month'],
                'unique_together': {('month', 'admin')},
            },
        ),
    ]
