# Generated by Django 5.0.7 on 2025-07-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NikahFlow', '0014_solemnisationbooking_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solemnisationbooking',
            name='specific_time',
        ),
    ]
